name: iil-dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - pip:
    - -e anguilla
    - -e iimrp
    - -e iipyper
    - -e notochord
    - -e tolvera
